// Auto-generated by scripts/load-affiliations.mjs — do not edit by hand.
// Source: Affiliations.csv (32 entries, 5 groups).

export type AffiliationGroup = {
  type: string
  items: string[]
}

export const AFFILIATION_GROUPS: readonly AffiliationGroup[] = [
  {
    type: 'Center',
    items: [
      'Brain Research Center',
      'Center for Companion Animal Studies',
      'Center for Vector Borne Infectious Diseases',
      'Flint Animal Cancer Center',
      'Orthopaedic Research Center',
      'Prion Research Center',
      'Research Innovation Center',
    ],
  },
  {
    type: 'Institute',
    items: [
      'Data Science Research Institute',
      'Infectious Disease Research Center',
      'One Health Institute',
      'Translational Medicine Institute',
    ],
  },
  {
    type: 'Laboratory',
    items: [
      'Animal Reproduction and Biotechnology Laboratory',
      'Equine Reproduction Laboratory',
      'Mycobacterial Research Laboratories',
      'Preclinical Surgical Research Lab',
      'Veterinary Diagnostic Laboratory',
    ],
  },
  {
    type: 'Program',
    items: [
      'Cell & Molecular Biology Program',
      'CURE Lab',
      'DVM/PhD Program',
      'HICAHS',
      'Honors Program',
      'MAP ERC',
      'Veterinary Summer Scholars Program',
      'Young Investigator\'s Program',
    ],
  },
  {
    type: 'Training Grant',
    items: [
      'CCTSI T32',
      'IDRRTP T32',
      'IMSD T32',
      'MARC T34',
      'MSTP T32',
      'Post-DVM T32',
      'PREP R25',
      'qCMB T32',
    ],
  },
] as const

export const ALL_AFFILIATIONS: readonly string[] = AFFILIATION_GROUPS.flatMap(
  (g) => g.items
)
