#!/usr/bin/env node
// Reads CVMBS-Faculty.csv from the repo root and emits a Supabase migration
// that upserts every row into the `faculty` table.
//
// Usage:  node scripts/load-faculty.mjs
// Output: supabase/migrations/2026-09-28_load_faculty.sql
//
// The generated SQL is idempotent: it upserts on `email`, and on conflict it
// only refreshes name/department/is_active — Green Labs flags and profile_id
// on existing rows are preserved.

import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))
const repoRoot = join(here, '..')

const CSV_PATH = join(repoRoot, 'CVMBS-Faculty.csv')
const OUT_PATH = join(repoRoot, 'supabase/migrations/2026-09-28_load_faculty.sql')

// Whitelist of valid department names — must match `departments.name` exactly.
// The CSV is expected to already hold canonical values; anything else is a typo
// caller should fix in the CSV rather than papering over here.
const VALID_DEPTS = new Set([
  'Biomedical Sciences',
  'Clinical Sciences',
  'Environmental & Radiological Health Sciences',
  'Microbiology, Immunology, and Pathology',
])

// Minimal RFC-4180 CSV parser — handles quoted commas but nothing exotic.
function parseCsv(text) {
  const rows = []
  let field = ''
  let row = []
  let inQuotes = false
  for (let i = 0; i < text.length; i++) {
    const c = text[i]
    if (inQuotes) {
      if (c === '"' && text[i + 1] === '"') {
        field += '"'
        i++
      } else if (c === '"') {
        inQuotes = false
      } else {
        field += c
      }
    } else if (c === '"') {
      inQuotes = true
    } else if (c === ',') {
      row.push(field)
      field = ''
    } else if (c === '\n') {
      row.push(field)
      rows.push(row)
      row = []
      field = ''
    } else if (c === '\r') {
      // ignore — handled by \n
    } else {
      field += c
    }
  }
  if (field.length || row.length) {
    row.push(field)
    rows.push(row)
  }
  return rows
}

// Uppercase the first letter of each name segment (split on space/hyphen/'),
// leave the rest of the segment untouched. This preserves human-entered mixed
// case (McCue, MacDonald, O'Brien, DiRenzo) while still fixing all-lowercase
// entries like "ashley" → "Ashley".
function normalizeName(name) {
  return name
    .trim()
    .replace(/\s+/g, ' ')
    .split(/([-\s'])/)
    .map((seg) => (seg.length && /[a-z]/.test(seg[0]) ? seg[0].toUpperCase() + seg.slice(1) : seg))
    .join('')
}

function sqlString(s) {
  return "'" + String(s).replace(/'/g, "''") + "'"
}

function main() {
  const raw = readFileSync(CSV_PATH, 'utf8')
  const rows = parseCsv(raw)
  const [header, ...data] = rows

  const idx = Object.fromEntries(header.map((h, i) => [h.trim(), i]))
  const required = ['Last Name', 'First Name', 'Email', 'Department']
  for (const col of required) {
    if (!(col in idx)) throw new Error(`CSV missing required column: ${col}`)
  }

  const skipped = []
  const ready = []

  for (const row of data) {
    if (row.every((c) => !c || !c.trim())) continue // blank line
    const last = (row[idx['Last Name']] ?? '').trim()
    const first = (row[idx['First Name']] ?? '').trim()
    const email = (row[idx['Email']] ?? '').trim().toLowerCase()
    const deptRaw = (row[idx['Department']] ?? '').trim()

    if (!last || !first || !email) {
      skipped.push({ reason: 'missing name/email', row })
      continue
    }
    if (!deptRaw) {
      skipped.push({ reason: 'blank department', row: `${first} ${last} <${email}>` })
      continue
    }
    if (!VALID_DEPTS.has(deptRaw)) {
      skipped.push({ reason: `unknown department "${deptRaw}"`, row: `${first} ${last} <${email}>` })
      continue
    }
    const fullName = `${normalizeName(first)} ${normalizeName(last)}`
    ready.push({ fullName, email, deptCanonical: deptRaw })
  }

  // Compose SQL
  const valueRows = ready
    .map(
      ({ fullName, email, deptCanonical }) =>
        `  (${sqlString(fullName)}, ${sqlString(email)}, ${sqlString(deptCanonical)})`
    )
    .join(',\n')

  const sql = `-- Faculty roster load — generated by scripts/load-faculty.mjs
-- Source: CVMBS-Faculty.csv (${ready.length} rows loaded, ${skipped.length} skipped).
-- Idempotent: upserts on email; preserves Green Labs flags + profile_id on existing rows.

BEGIN;

WITH incoming (full_name, email, dept_name) AS (
  VALUES
${valueRows}
),
resolved AS (
  SELECT
    i.full_name,
    i.email,
    d.id AS department_id
  FROM incoming i
  JOIN departments d ON d.name = i.dept_name
)
INSERT INTO faculty (full_name, email, department_id, is_active)
SELECT full_name, email, department_id, TRUE
FROM resolved
ON CONFLICT (email) DO UPDATE
SET full_name     = EXCLUDED.full_name,
    department_id = EXCLUDED.department_id,
    is_active     = TRUE;

COMMIT;
`

  writeFileSync(OUT_PATH, sql)

  console.log(`Wrote ${OUT_PATH}`)
  console.log(`  loaded:  ${ready.length}`)
  console.log(`  skipped: ${skipped.length}`)
  if (skipped.length) {
    console.log('  skipped rows:')
    for (const s of skipped) {
      console.log(`    - [${s.reason}] ${typeof s.row === 'string' ? s.row : JSON.stringify(s.row)}`)
    }
  }
}

main()
